In [1]:
import pandas as pd
from collections import defaultdict
from tqdm import tqdm
import random
import seaborn as sns


random.seed(0)

In [2]:
# nb nodes, the n biggest anime watcher
NB_USERS = 500

In [3]:
medianWatcherDf = pd.read_csv("./Data/animeList_selected.csv", index_col=0)
medianWatcherDf = medianWatcherDf.reset_index(drop=True)
medianWatcherDf['nbAnimeWatched'] = medianWatcherDf.groupby('username')['username'].transform('count')

medianWatcherDf = medianWatcherDf.sort_values(by='nbAnimeWatched', ascending=False)

print(medianWatcherDf['nbAnimeWatched'].median())

biggestWatcher = medianWatcherDf['username'].unique()
biggestWatcher = biggestWatcher.tolist()

97.0

In [4]:

medianWatcherDf[3750000:].head(30)

,username,anime_id,my_watched_episodes,my_score,my_status,my_rewatching,my_rewatching_ep,my_tags,nbAnimeWatched
4015617,_Ami_,226,13,5,2,NaN,0,Action,97.0
4015618,_Ami_,237,0,0,6,0.0,0,NaN,97.0
4015619,_Ami_,355,24,6,2,0.0,0,"Action, Fantasy",97.0
4015620,_Ami_,356,7,4,4,0.0,0,NaN,97.0
4015621,_Ami_,430,1,7,2,0.0,0,Shounen,97.0
4015622,_Ami_,431,1,9,2,0.0,0,Ghibli,97.0
4015623,_Ami_,523,1,0,2,0.0,0,Ghibli,97.0
4015624,_Ami_,578,0,0,6,0.0,0,NaN,97.0
4015625,_Ami_,849,14,9,2,0.0,0,"Comedy, Mystery",97.0
4015646,_Ami_,5114,64,10,2,NaN,0,Shounen,97.0
4015648,_Ami_,5630,11,9,2,NaN,0,Action,97.0
4015609,_Ami_,1,1,0,3,NaN,0,"Adventure,Space",97.0
4015676,_Ami_,32281,0,0,6,0.0,0,NaN,97.0
4015669,_Ami_,16592,0,0,6,0.0,0,NaN,97.0
4015670,_Ami_,17895,0,0,6,0.0,0,NaN,97.0
4015671,_Ami_,23273,0,0,6,0.0,0,NaN,97.0
4015672,_Ami_,23283,0,0,6,0.0,0,NaN,97.0
4015673,_Ami_,23289,12,9,2,0.0,0,comedy,97.0
4015674,_Ami_,28999,0,0,6,0.0,0,NaN,97.0
4015675,_Ami_,31043,0,0,6,0.0,0,NaN,97.0
4015677,_Ami_,66,3,0,4,0.0,0,NaN,97.0
4015649,_Ami_,6347,13,8,2,0.0,0,"Comedy,Parody",97.0
4015678,_Ami_,71,6,5,4,0.0,0,NaN,97.0
4015679,_Ami_,2966,0,0,6,0.0,0,NaN,97.0
4015680,_Ami_,101,12,9,2,0.0,0,"Key,Drama",97.0
4015681,_Ami_,1195,13,7,2,NaN,0,Romance,97.0
4015682,_Ami_,1530,24,10,2,NaN,0,Key,97.0
4015683,_Ami_,2924,12,9,2,0.0,0,"Drama, Romance",97.0
4015684,_Ami_,4181,24,10,2,NaN,0,Key,97.0
4015668,_Ami_,16498,0,0,6,0.0,0,NaN,97.0

In [5]:
print(biggestWatcher.index('_Ami_'))
print(biggestWatcher[29112-100:29112+100])


biggestWatcherCenteredOnMedian = biggestWatcher[29112-20000:29112+20000:80]

biggestWatcherCenteredOnMedianSample = biggestWatcherCenteredOnMedian

29112
['zou136', 'natiko', '_Isaac_', 'Bobby_Deimos', 'Den_serb', 'Dellirium', 'shizaman', 'Hadrins', 'Qinchi', 'Nitzy', 'Sunsaegnim', 'designed', 'DarKraD_10', 'akuryuus', 'Rograck', 'nate23nate23', 'OzzyOtaku', 'Tarai', 'AmuKitten', 'gumplug', 'marlo', 'jheamuel123', 'kal-el', 'ciaomaya', 'PoiiPoii', 'Epexion', 'Adov', 'grifatmal', 'Caju144', 'Storm_Gamer', 'Falqiore', 'michaelclark09', 'Vampire_Lord', 'RitsukaAP', 'loveleonfan', 'ragnaroks', 'CuccoSlayer', 'KanimeD', 'zetzuei', 'Katyushkiz', 'AltayrEvergarden', 'Rasti', 'Henshin_Ikeda', 'Juanda22Q', 'Iflybees', 'StrayCat216', 'Azusa-G', 'ArekkuseiRaz', 'aznriptide859', 'OkazakiSan', 'Shizako', 'Norco', 'Ta-Taa', 'JT_412', 'pwrules', 'itachigo', 'Yuyu-chan', 'Boris_P', 'Snejk', 'Necessity4fun', 'Dravania', 'MattyFTW', 'willsaint', 'andrew_24', 'Carru', 'Ryujii1995', 'Afnan_Alwan', 'Mexii', 'Kurohoro', 'Kage-Inazuma', 'sxymegger', 'Vegaplus', 'Slerian', 'Boxwithcola', 'kolobchara', 'Savepoint', 'Tawm', 'Sevary', 'Tetsuya95', 'FoodforFish', 'FMA15', 'MajikkuMich', 'Phoepal', 'sasukesadaf', 'CptDrRev', 'Devmastuh', 'Clauux', 'MystikSk8', 'sonazki', 'hazlove', 'Tomstrife', 'BUGS-BUNNY', 'arletti', 'Aguileitus', 'Onez', 'zfpndngn', 'Davieoua', 'Vitavili', 'Ryle-chan', 'mrocznyluzio', '_Ami_', 'Grande_Swag', 'M2VASH', 'excaliburuu', 'Ramen', 'Standamon318', 'crispee', 'PSYCH0_C10WN', 'dusting010', 'psygol', 'HimitsuKoe', 'TKavney92', 'Mrbatata', 'Nannami98', 'mahermatrix', 'GePilar_', 'pao123', 'Creed13', 'RinonNinqueon', 'nlBorn', 'Jakestr69', 'ILuvAnime12', 'Artemon', 'mejordan1993', 'Lunatic-kr', 'Ahio1', 'Aldo', 'FuyuYurei', 'trinisete', 'CardcaptorMadoka', 'ZeroBlut', 'puchacamilo', 'Proga', 'Towbie', 'lvlln', 'Nylia', 'Deyeaz', 'ColdChaos', 'Marevo', 'Chag', 'Will-Sama', 'Perdedore', 'Svart', 'Holy-Night', 'Slykain', 'miss_drakula', 'schone', 'afrodestinyfan', 'DrewTheDude', 'floralwinry', 'fishstick3000', 'Sallymancan', 'Vorsha', 'amp070', 'Rambut_Legend', 'Paltheos', 'Hierophobic', 'GinSuri', 'xXChaosEaterXx', 'kirito1452', 'Dub-cat', 'ANIMkka', 'Yuu25', 'Luxuria69', 'Kiragaya', 'chesron', 'The_Asch', 'Waterbender899', 'GeNyaa', 'FoyFoyy', 'Playboy', 'Nicolas-', 'GhostFH', 'Thombs', 'theoriginalgibly', 'apparently', 'Yoda_NG', 'Doodle_m', 'Noitamina', 'Konfig', 'discofroman', 'Blair431', 'MothaSun', 'rennna', 'naota46', 'KanadeMizuni', 'TheCaylos', 'Cuscuz', 'okmijnuha', 'Lord-SephirothVI', 'Rikumoon123', 'chelomirrey96', 'Tenk', 'Denisecvo', 'Knight_Shift', 'laurakbye', 'Pyrowe', 'elenasdf_', 'marymeechan369', 'OnyLovestone']

In [6]:
anime_selected = pd.read_csv("./Data/animeList_selected.csv", index_col=0)
anime_selected = anime_selected.reset_index(drop=True)

# Filter
anime_selected = anime_selected[anime_selected['username'].isin(biggestWatcherCenteredOnMedianSample)]


anime_selected.head(5)

,username,anime_id,my_watched_episodes,my_score,my_status,my_rewatching,my_rewatching_ep,my_tags
2563,jukugo,21,125,2,3,0.0,0,NaN
2564,jukugo,120,26,5,2,0.0,0,comedy
2565,jukugo,249,117,2,3,0.0,0,NaN
2566,jukugo,269,100,3,3,0.0,0,NaN
2567,jukugo,853,26,7,2,0.0,0,"school, comedy, parody, shounen ai"

In [7]:
username_and_anime_id = anime_selected.drop(columns=["my_status", "my_watched_episodes", "my_rewatching", "my_rewatching_ep", "my_tags"])

In [8]:
username_and_anime_id

              username  anime_id  my_score
2563            jukugo        21         2
2564            jukugo       120         5
2565            jukugo       249         2
2566            jukugo       269         3
2567            jukugo       853         7
...                ...       ...       ...
7364288  AnimeRagnarok     20787         6
7364289  AnimeRagnarok     17265         9
7364290  AnimeRagnarok      6547        10
7364291  AnimeRagnarok     28851         9
7364292  AnimeRagnarok     10165         9

[49487 rows x 3 columns]

In [9]:
anime = pd.read_csv('./Data/anime_cleaned.csv')
username_and_anime_id = username_and_anime_id.merge(anime, on="anime_id")

In [10]:
username_and_anime_id = username_and_anime_id[["username", "genre"]]
username_and_anime_id

           username                                              genre
0            jukugo  Action, Adventure, Comedy, Super Power, Drama,...
1      Aria-da-Capo  Action, Adventure, Comedy, Super Power, Drama,...
2          faresbrk  Action, Adventure, Comedy, Super Power, Drama,...
3        TheShouyou  Action, Adventure, Comedy, Super Power, Drama,...
4             Amppu  Action, Adventure, Comedy, Super Power, Drama,...
...             ...                                                ...
49482      XiTBeasT  Comedy, Ecchi, Fantasy, Harem, Romance, School...
49483   mangetsuxii  Comedy, Ecchi, Fantasy, Harem, Romance, School...
49484   vinwater678  Comedy, Ecchi, Fantasy, Harem, Romance, School...
49485    destiny42s  Comedy, Ecchi, Fantasy, Harem, Romance, School...
49486  ThePrototype  Comedy, Ecchi, Fantasy, Harem, Romance, School...

[49487 rows x 2 columns]

In [11]:
tmp = [[y.replace(" ", "") for y in x.split(",")] for x in username_and_anime_id["genre"]]
username_and_anime_id["genre"] = tmp
username_and_anime_id

           username                                              genre
0            jukugo  [Action, Adventure, Comedy, SuperPower, Drama,...
1      Aria-da-Capo  [Action, Adventure, Comedy, SuperPower, Drama,...
2          faresbrk  [Action, Adventure, Comedy, SuperPower, Drama,...
3        TheShouyou  [Action, Adventure, Comedy, SuperPower, Drama,...
4             Amppu  [Action, Adventure, Comedy, SuperPower, Drama,...
...             ...                                                ...
49482      XiTBeasT  [Comedy, Ecchi, Fantasy, Harem, Romance, Schoo...
49483   mangetsuxii  [Comedy, Ecchi, Fantasy, Harem, Romance, Schoo...
49484   vinwater678  [Comedy, Ecchi, Fantasy, Harem, Romance, Schoo...
49485    destiny42s  [Comedy, Ecchi, Fantasy, Harem, Romance, Schoo...
49486  ThePrototype  [Comedy, Ecchi, Fantasy, Harem, Romance, Schoo...

[49487 rows x 2 columns]

In [14]:
genreWatched = username_and_anime_id.explode("genre")
genreWatched

           username       genre
0            jukugo      Action
0            jukugo   Adventure
0            jukugo      Comedy
0            jukugo  SuperPower
0            jukugo       Drama
...             ...         ...
49486  ThePrototype     Fantasy
49486  ThePrototype       Harem
49486  ThePrototype     Romance
49486  ThePrototype      School
49486  ThePrototype     Vampire

[249264 rows x 2 columns]

In [17]:
genreList = genreWatched["genre"].unique().tolist()
print(len(genreList))
genreList

37

['Action',
 'Adventure',
 'Comedy',
 'SuperPower',
 'Drama',
 'Fantasy',
 'Shounen',
 'SliceofLife',
 'Romance',
 'Shoujo',
 'Historical',
 'Demons',
 'Supernatural',
 'Magic',
 'Harem',
 'School',
 'Ecchi',
 'Sports',
 'MartialArts',
 'Parody',
 'Sci-Fi',
 'Space',
 'Dementia',
 'Psychological',
 'Mecha',
 'Police',
 'Seinen',
 'Samurai',
 'Military',
 'Horror',
 'Mystery',
 'Vampire',
 'Music',
 'Thriller',
 'Josei',
 'Game',
 'Kids']

In [26]:
genreList_T = genreWatched.pivot(columns='genre', values="username")
genreList_T=genreList_T.notnull().astype("int")
genreList_T

genre,Action,Adventure,Comedy,Dementia,Demons,Drama,Ecchi,Fantasy,Game,Harem,...,Seinen,Shoujo,Shounen,SliceofLife,Space,Sports,SuperPower,Supernatural,Thriller,Vampire
0,1,1,1,0,0,1,0,1,0,0,...,0,0,1,0,0,0,1,0,0,0
1,1,1,1,0,0,1,0,1,0,0,...,0,0,1,0,0,0,1,0,0,0
2,1,1,1,0,0,1,0,1,0,0,...,0,0,1,0,0,0,1,0,0,0
3,1,1,1,0,0,1,0,1,0,0,...,0,0,1,0,0,0,1,0,0,0
4,1,1,1,0,0,1,0,1,0,0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49482,0,0,1,0,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,1
49483,0,0,1,0,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,1
49484,0,0,1,0,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,1
49485,0,0,1,0,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,1
49486,0,0,1,0,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,1

In [28]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

supports = apriori(genreList_T, min_support=0.1,max_len=3, use_colnames=True)
supports.sort_values(by="support", ascending=False).head(50)

/home/ambroise/.local/lib/python3.10/site-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support                       itemsets
0   0.485380                       (Action)
2   0.480369                       (Comedy)
14  0.362823                 (Supernatural)
8   0.347020                      (Romance)
3   0.340999                        (Drama)
9   0.295815                       (School)
11  0.287894                      (Shounen)
4   0.243620                      (Fantasy)
1   0.230141                    (Adventure)
10  0.216158                       (Sci-Fi)
29  0.215855               (Comedy, School)
6   0.209974                      (Mystery)
16  0.209105               (Comedy, Action)
28  0.203872              (Comedy, Romance)
20  0.195041              (Shounen, Action)
22  0.186736         (Supernatural, Action)
30  0.184776              (Comedy, Shounen)
12  0.178633                  (SliceofLife)
15  0.176006            (Action, Adventure)
18  0.170247              (Action, Fantasy)
37  0.169580              (Romance, School)
33  0.160264               (Drama, Romance)
7   0.146059                (Psychological)
19  0.141997               (Sci-Fi, Action)
13  0.139794                   (SuperPower)
24  0.138360           (Adventure, Fantasy)
23  0.136460            (Comedy, Adventure)
17  0.135409                (Drama, Action)
32  0.128781         (Comedy, Supernatural)
44  0.127912      (Comedy, Romance, School)
21  0.127124           (SuperPower, Action)
31  0.124962          (Comedy, SliceofLife)
36  0.124235        (Supernatural, Mystery)
43  0.118354      (Comedy, Shounen, Action)
40  0.117607    (Comedy, Action, Adventure)
26  0.117384                (Comedy, Drama)
39  0.113363          (School, SliceofLife)
25  0.112130           (Shounen, Adventure)
34  0.111747          (Drama, Supernatural)
35  0.111464             (Shounen, Fantasy)
5   0.108453                        (Magic)
27  0.104977              (Comedy, Fantasy)
42  0.104492   (Shounen, Action, Adventure)
41  0.104250   (Action, Adventure, Fantasy)
38  0.103078        (Supernatural, Romance)
45  0.102350  (Comedy, School, SliceofLife)

In [44]:
# compute association rules
rules = association_rules(supports, min_threshold=0.5)
rules.sort_values(by="conviction", ascending=True).head(30)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
5,(Supernatural),(Action),0.362823,0.485380,0.186736,0.514676,1.060356,0.010629,1.060363,0.089332
9,(Romance),(Comedy),0.347020,0.480369,0.203872,0.587492,1.223003,0.037174,1.259688,0.279243
6,(Adventure),(Comedy),0.230141,0.480369,0.136460,0.592941,1.234345,0.025907,1.276549,0.246609
28,"(Shounen, Action)",(Comedy),0.195041,0.480369,0.118354,0.606817,1.263233,0.024663,1.321603,0.258871
26,"(Comedy, Shounen)",(Action),0.184776,0.485380,0.118354,0.640529,1.319645,0.028668,1.431605,0.297121
11,(Shounen),(Comedy),0.287894,0.480369,0.184776,0.641819,1.336098,0.046481,1.450752,0.353250
2,(Sci-Fi),(Action),0.216158,0.485380,0.141997,0.656913,1.353400,0.037078,1.499970,0.333128
18,"(Action, Adventure)",(Comedy),0.176006,0.480369,0.117607,0.668197,1.391010,0.033059,1.566086,0.341141
3,(Shounen),(Action),0.287894,0.485380,0.195041,0.677476,1.395764,0.055303,1.595602,0.398180
1,(Fantasy),(Action),0.243620,0.485380,0.170247,0.698822,1.439742,0.051999,1.708691,0.403806
12,(SliceofLife),(Comedy),0.178633,0.480369,0.124962,0.699548,1.456272,0.039153,1.729496,0.381456
10,(School),(Comedy),0.295815,0.480369,0.215855,0.729695,1.519031,0.073754,1.922387,0.485221
22,"(Adventure, Fantasy)",(Action),0.138360,0.485380,0.104250,0.753469,1.552327,0.037093,2.087443,0.412940
31,"(School, Romance)",(Comedy),0.169580,0.480369,0.127912,0.754290,1.570231,0.046452,2.114814,0.437310
0,(Adventure),(Action),0.230141,0.485380,0.176006,0.764773,1.575617,0.064300,2.187759,0.474539
13,(Mystery),(Supernatural),0.209974,0.362823,0.124235,0.591666,1.630731,0.048051,1.560431,0.489576
14,(School),(Romance),0.295815,0.347020,0.169580,0.573263,1.651958,0.066926,1.530169,0.560446
30,"(Comedy, School)",(Romance),0.215855,0.347020,0.127912,0.592586,1.707639,0.053006,1.602741,0.528469
17,"(Comedy, Adventure)",(Action),0.136460,0.485380,0.117607,0.861839,1.775597,0.051372,3.724790,0.505835
4,(SuperPower),(Action),0.139794,0.485380,0.127124,0.909367,1.873515,0.059271,5.678056,0.542015
33,"(School, SliceofLife)",(Comedy),0.113363,0.480369,0.102350,0.902852,1.879499,0.047894,5.348867,0.527773
24,"(Shounen, Adventure)",(Action),0.112130,0.485380,0.104492,0.931880,1.919897,0.050066,7.554567,0.539650
27,"(Comedy, Action)",(Shounen),0.209105,0.287894,0.118354,0.566003,1.966014,0.058154,1.640809,0.621267
25,"(Action, Adventure)",(Shounen),0.176006,0.287894,0.104492,0.593685,2.062168,0.053821,1.752598,0.625094
29,"(Comedy, Romance)",(School),0.203872,0.295815,0.127912,0.627416,2.120974,0.067604,1.890003,0.663861
15,(SliceofLife),(School),0.178633,0.295815,0.113363,0.634615,2.145311,0.060521,1.927243,0.649974
23,"(Shounen, Action)",(Adventure),0.195041,0.230141,0.104492,0.535744,2.327892,0.059605,1.658263,0.708641
20,"(Action, Adventure)",(Fantasy),0.176006,0.243620,0.104250,0.592308,2.431282,0.061371,1.855273,0.714440
19,(Adventure),"(Comedy, Action)",0.230141,0.209105,0.117607,0.511019,2.443836,0.069483,1.617436,0.767423
16,"(Comedy, Action)",(Adventure),0.209105,0.230141,0.117607,0.562428,2.443836,0.069483,1.759386,0.747011